no-review-needed:
  - "**"

june-leetcoding-challenge:
  - "explore/other/card/june-leetcoding-challenge/**/*"

july-leetcoding-challenge:
  - "explore/other/card/july-leetcoding-challenge/**/*"

august-leetcoding-challenge:
  - "explore/other/card/august-leetcoding-challenge/**/*"

september-leetcoding-challenge:
  - "explore/other/card/september-leetcoding-challenge/**/*"

october-leetcoding-challenge:
  - "explore/other/card/october-leetcoding-challenge/**/*"

november-leetcoding-challenge:
  - "explore/other/card/november-leetcoding-challenge/**/*"
