---
language: go
go:
  - 1.12.x
  - 1.13.x
  - tip
sudo: false
before_install:
  - go get -v ./...
script:
  - go test -race -covermode=atomic -coverprofile=coverage.txt ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - GO111MODULE=on
